### ISSUE TITLE
Motor Rotation Change Mid-flight

### ISSUE THREAD

**Issue by Pedro-Roque** [PX4/sapog#10]
Hello folks,

I would like to know if the motor inversion option is available during flight with UAVCAN Protocol, so we can change the motor rotation mid-flight.

Thank you in advance!

**Comment by pavel-kirienko** [comment]
Hi Pedro,

UAVCAN does support this feature - reverse rotation can be achieved with negative setpoint value. See http://uavcan.org/Specification/7._List_of_standard_data_types/#rawcommand

However, it is not supported in PX4ESC yet - it would require to add some logic for handling proper deceleration of the rotor and then starting it in the opposite direction. It may be added in the future.

**Comment by Pedro-Roque** [comment]
Thank you very much @pavel-kirienko !

Where can I buy these ESC? Or how to get hands on one of them? I am interested on that topic and could potentially develop firmware to take care of that!

**Comment by pavel-kirienko** [comment]
PX4ESC-based designs will become available approximately by the end of the
year.

**Comment by Pedro-Roque** [comment]
Thank you @pavel-kirienko 

I will report back when I get my hands on one of these and start developing for it!

**Comment by pavel-kirienko** [comment]
Implemented in [PX4ESC](https://github.com/Zubax/px4esc).
