### ISSUE TITLE
Increase the space allocated for bootloader to 16K

### ISSUE THREAD

**Issue by pavel-kirienko** [PX4/sapog#13]
@bendyer @davids5 We currently have only 8K reserved for the bootloader, which is enough for now but precludes future growth. I suggest to reserve 16K of flash for the bootloader instead - this will enable us to possibly add USB bootloader or some other feature in the future, if the need arises.

**Comment by LorenzMeier** [comment]
Yes, that makes a lot of sense for the boards where we have enough flash. I do care about ensuring that a non-USB variant fits in 8K though.

**Comment by pavel-kirienko** [comment]
Yes we do have enough flash on Pixhawk ESC v1.4 (256K, about 150K used).

**Comment by davids5** [comment]
We already support 8KiB and 16KiB builds. It depends on the SoC the F1 are 8KiB the F4 are 16KiB. The Uavcannode app on the STM32F103 would not allow for any user code if it had to have a 16K bootloader. I say we go case by case and but always support 8K for the low memory parts.
