### ISSUE TITLE
 sapog development environment 

### ISSUE THREAD

**Issue by liuchangmaker** [PX4/sapog#20]
Hello!I build sapog development environment encountered many problems, can you give me a detail development environment development steps.thank you!

**Comment by j3qq4hch** [comment]
Have you tried creating new Eclipse project from makefile? Was it any succesfull?

**Comment by pavel-kirienko** [comment]
Pease either describe what exact problems you encountered, or use the Bisthromatic virtual machine (see Readme).

**Comment by pavel-kirienko** [comment]
Also keep in mind that you can't use Windows.

**Comment by j3qq4hch** [comment]
>>Also keep in mind that you can't use Windows.

Is that true even in the case I bother to install all *nix environment?

**Comment by pavel-kirienko** [comment]
Well, OK, you can use Windows if you really know what you're doing. YMMV.

**Comment by pavel-kirienko** [comment]
Feel free to re-open if the question is still valid.
