### ISSUE TITLE
[Feature request]Add support DSHOT signal input

### ISSUE THREAD

**Issue by Linjieqiang** [PX4/sapog#25]
[Feature request]Add support DSHOT signal input.

**Comment by pavel-kirienko** [comment]
Thanks, @Linjieqiang.

If anybody out there is willing to implement this, I would gladly accept a pull request.

**Comment by Linjieqiang** [comment]
Do you think it's necessary to support this feature?@pavel-kirienko

**Comment by pavel-kirienko** [comment]
I think it is definitely not a required thing because we have CAN.

**Comment by Linjieqiang** [comment]
OK.I see..I will close this issue.
