### ISSUE TITLE
segfaults during linking

### ISSUE THREAD

**Issue by dusan19** [PX4/sapog#26]
When I am compiling the main binary using the make command I get the following error
```
Linking build/io.px4.sapog.elf
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
```
I am using gcc version
`gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
`
and ld version
`GNU ld (GNU Binutils for Ubuntu) 2.26.1`

How could I fix the problem?
Thanks

**Comment by pavel-kirienko** [comment]
Switch to GCC 4.9, as suggested by README
