### ISSUE TITLE
esc_setpoint_raw is offset from rpm feedback.

### ISSUE THREAD

**Issue by keenanjohnson** [PX4/sapog#29]
I've noticed that in the PX4 logs of the sapog motor driver firmware, the esc_rpm and esc_setpoint_raw seem to be off by some set factor.

Does anyone know why that might be?

![image](https://user-images.githubusercontent.com/2559382/40145838-36458cf6-5918-11e8-8fbb-254033cde228.png)

**Comment by pavel-kirienko** [comment]
Please make sure that the number of poles is configured correctly.

**Comment by keenanjohnson** [comment]
I've confirmed that this is the case. This test data comes from this motor: http://store-en.tmotor.com/goods.php?id=353 which is listed as 22 poles. That's what I have configured in the parameters.

**Comment by pavel-kirienko** [comment]
Assuming that you're using the default PWM frequency of 60 kHz, the maximum mechanical speed for your motor is 6900 RPM, which seems to be compatible with your application (judging by the graphs). So I would suggest making sure that the PID controller is configured properly. You can use the CLI to command the motor a particular speed and observe how quickly it is reached. The speed can be plotted using the UAVCAN GUI Tool.

**Comment by keenanjohnson** [comment]
Why would that affect the rpm feedback reading?

**Comment by pavel-kirienko** [comment]
I am suspecting that the reading is correct, and the divergence is caused by the ESC not reaching the speed setpoint due to misconfigured RPM PID controller.

**Comment by keenanjohnson** [comment]
What sort of parameters would cause that?

We've verified that our feedback is correct via an external tachometer. So we're confused why the setpoint is so much higher still.
