### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by BreederBai** [PX4/sapog#31]
This prompt error makes me feel confused, I don't know how to solve this problem, my toolchain is GCC ARM 4.9.3
![image](https://user-images.githubusercontent.com/27894314/43627544-6efe513c-9729-11e8-87b3-e6199984e160.png)

**Comment by LorenzMeier** [comment]
Your ARM GCC version is very, very old. You will need to update it.

**Comment by pavel-kirienko** [comment]
> You will need to update it.

...to GCC 7.2. And I need to update README.

**Comment by BreederBai** [comment]
Thank you for your answer, but why not choose to be compatible with the old toolchain, the old toolchain is still used by many people.

**Comment by pavel-kirienko** [comment]
"many people" should get on board with the rest of the world.

**Comment by LorenzMeier** [comment]
4.9 is 4 years old. Most software developers in the drone space were still students at that time. Time to move on!

**Comment by BreederBai** [comment]
Ok, I am using 5.4 and I will get this error. But your reason has convinced me.
