### ISSUE TITLE
On which pin UART2 is？

### ISSUE THREAD

**Issue by BreederBai** [PX4/sapog#32]
I want to learn ChibiOS, and “sapog” is a very good example. I want to use USART2, but I can't determine which pin USART2 is on. The data sheet of STM32F105 shows that PA2, PA3, PD5, PD6 can be used for USART2. I think there should be a file that specifies the mapping between pins and USART2. But I am not sure what I think is right.

**Comment by pavel-kirienko** [comment]
GPIO remappings are configured here: https://github.com/PX4/sapog/blob/master/firmware/src/board/board.cpp#L221-L233

By default, USART2 is not remapped.
