### ISSUE TITLE
Missed mid-flight rotation feature

### ISSUE THREAD

**Issue by bioniwulf** [PX4/sapog#48]
Hi, px4 community!

For my thruster that based on sapog software mid-flight rotation change is very important.
I have noticed that this feature was added in December of 2016 #10 , but I cannot find any sign of it in the repository.

Few months later according to issue #12 you decided to rollback the repository to some previous version.
Is it possible that this added feature was missed during the migration?

**Comment by pavel-kirienko** [comment]
Ad-hoc reversal was never implemented in Sapog, and it is not currently on the roadmap. Maybe consider Myxa or other Telega-based controllers instead, where this capability is implemented (Telega has been designed by the same team but it is not open-source).

**Comment by bioniwulf** [comment]
> Ad-hoc reversal was never implemented in Sapog, and it is not currently on the roadmap. Maybe consider Myxa or other Telega-based controllers instead, where this capability is implemented (Telega has been designed by the same team but it is not open-source).

Thank you for the answer! Ok, will implement it on our side.
Does it make sense to do make pull request with this feature in the master?

P.S. Is Mitochondrik LV commercially available right now? I checked Zubax site ([link](https://zubax.com/products/mitochondrik-lv)) and market release was planned on Q4 2020 with no any further news.

**Comment by pavel-kirienko** [comment]
>Does it make sense to do make pull request with this feature in the master?

Sure, but maybe not right now, because we are soon planning to merge our fork where we've been working on v3.0.

> Is Mitochondrik LV commercially available right now?

Yes. If you'd like to discuss your project, feel free to drop us a msg to sales@zubax.com.

**Comment by bioniwulf** [comment]
Pavel, thank you for answers! It was helpful.
